=== dragontwiz/xmlpro/obekt66.dtd
<!ELEMENT AutoCatalogue (listing,technical,features,review)>
<!ELEMENT listing (region,city,price,date)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT technical (brand,model,year,power,mileage,category,emissionStandard,color,transmission,enginetype)>
<!ELEMENT brand (#PCDATA)>
<!ATTLIST brand brandCode ID #REQUIRED>
<!ATTLIST brand years ID #REQUIRED>
<!ELEMENT model (#PCDATA)>
<!ATTLIST model power ID #REQUIRED>
<!ATTLIST model modelbrand IDREF #REQUIRED>
<!ELEMENT year (#PCDATA)>
<!ATTLIST year yearp IDREF #REQUIRED>
<!ELEMENT power (#PCDATA)>
<!ATTLIST power p IDREF #REQUIRED>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT emissionStandard (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT transmission (#PCDATA)>
<!ELEMENT enginetype (#PCDATA)>
<!ELEMENT features (safety,comfort,other,exterior,interior,security,specialised)>
<!ELEMENT safety (#PCDATA)>
<!ELEMENT comfort (#PCDATA)>
<!ELEMENT other (#PCDATA)>
<!ELEMENT exterior (#PCDATA)>
<!ELEMENT interior (#PCDATA)>
<!ELEMENT security (#PCDATA)>
<!ELEMENT specialised (#PCDATA)>
<!ELEMENT review (#PCDATA)>
<!ENTITY car1 "https://www.auto-data.net/images/f56/Alfa-Romeo-159-Sportwagon.jpg">

=== dragontwiz/xmlpro/Obekt 66.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="obekt66.xsl"?>
<!DOCTYPE AutoCatalogue SYSTEM "obekt66.dtd">
<AutoCatalogue>
    <listing>
        <region>Sofia-city</region>
        <city>Sofia</city>
        <price>11000</price>
        <date>20.02.2002</date>
    </listing>
    <technical>
        <brand brandCode="alfa" years="zerosix-twelve">Alfa Romeo</brand>
        <model modelbrand="alfa" power="medium">159</model>
        <year yearp="zerosix-twelve">2010</year>
        <power p="medium">150</power>
        <mileage>120000</mileage>
        <category>Sedan</category>
        <emissionStandard>Euro 5</emissionStandard>
        <color>Bordeaux</color>
        <transmission>Automatic</transmission>
        <enginetype>Diesel</enginetype>
    </technical>
    <features>
        <safety> ASC AFL ESP Park Assist Distronic </safety>
        <comfort> Navigation Klimatronic Klimatic Steering Wheel Heating Airmatic </comfort>
        <other> 4x4 7 seats Tuning LPG </other>
        <exterior> Panoramic Roof 2/3 Doors 4/5 Doors Metallic Alloy Wheels </exterior>
        <interior> Cloth Seats Leather Seats Right Wheel Drive </interior>
        <security> Alarm Armorred Toe hook </security>
        <specialised> Taxi For People With Dissabilities Ambulance Fridge </specialised>
    </features>
</AutoCatalogue>
